package com.bzaja.ljudskiresursiiposlovniprocesijavafx.resource;

public enum FxmlView {
    PRIJAVA("/prijava/Prijava.fxml"),
    GLAVNI_IZBORNIK("/glavniizbornik/GlavniIzbornik.fxml"),
    DRZAVE("/drzava/Drzave.fxml"),
    DODAJ_UREDI_DRZAVU("/drzava/DodajUrediDrzavu.fxml"),
    PRETRAZIVANJE_I_SORTIRANJE("/pretrazivanjeisortiranje/PretrazivanjeISortiranje.fxml"),
    POREZI("/porez/Porezi.fxml"),
    DODAJ_UREDI_POREZ("/porez/DodajUrediPorez.fxml"),
    ADMINISTRATOR_DASHBOARD("/dashboard/AdministratorDashboard.fxml"),
    OSOBLJE_DASHBOARD("/dashboard/OsobljeDashboard.fxml"),
    GRADOVI("/grad/Gradovi.fxml"),
    DODAJ_UREDI_GRAD("/grad/DodajUrediGrad.fxml"),
    ODJELI("/odjel/Odjeli.fxml"),
    DODAJ_UREDI_ODJEL("/odjel/DodajUrediOdjel.fxml"),
    RADNA_MJESTA("/radnomjesto/RadnaMjesta.fxml"),
    DODAJ_UREDI_RADNO_MJESTO("/radnomjesto/DodajUrediRadnoMjesto.fxml"),
    VRSTE_DODATAKA("/vrstadodatka/VrsteDodataka.fxml"),
    DODAJ_UREDI_VRSTU_DODATKA("/vrstadodatka/DodajUrediVrstuDodatka.fxml"),
    VRSTE_OBUSTAVA("/vrstaobustave/VrsteObustava.fxml"),
    DODAJ_UREDI_VRSTU_OBUSTAVE("/vrstaobustave/DodajUrediVrstuObustave.fxml"),
    VRSTE_PREKOVREMENIH_RADOVA("/vrstaprekovremenograda/VrstePrekovremenihRadova.fxml"),
    DODAJ_UREDI_VRSTU_PREKOVREMENOG_RADA("/vrstaprekovremenograda/DodajUrediVrstuPrekovremenogRada.fxml"),
    VRSTE_DAVANJA("/vrstadavanja/VrsteDavanja.fxml"),
    DODAJ_UREDI_VRSTU_DAVANJA("/vrstadavanja/DodajUrediVrstuDavanja.fxml"),
    VRSTE_OLAKSICA("/vrstaolaksice/VrsteOlaksica.fxml"),
    DODAJ_UREDI_VRSTU_OLAKSICE("/vrstaolaksice/DodajUrediVrstuOlaksice.fxml"),
    STUDENTSKI_POSLOVI_CJENIK("/studentskiposaocjenik/StudentskiPosloviCjenik.fxml"),
    DODAJ_UREDI_STUDENTSKI_POSAO_CJENIK("/studentskiposaocjenik/DodajUrediStudentskiPosaoCjenik.fxml"),
    ZAPOSLENICI("/zaposlenik/Zaposlenici.fxml"),
    DODAJ_ZAPOSLENIKA("/zaposlenik/DodajZaposlenika.fxml"),
    UREDI_ZAPOSLENIKA("/zaposlenik/UrediZaposlenika.fxml"),
    PROMJENA_LOZINKE_ZAPOSLENIKA("/zaposlenik/PromjenaLozinkeZaposlenika.fxml"),
    DAVANJA_ZAPOSLENIKA("/davanje/DavanjaZaposlenika.fxml"),
    DODAJ_UREDI_DAVANJE_ZAPOSLENIKA("/davanje/DodajUrediDavanjeZaposlenika.fxml"),
    DODATCI_ZAPOSLENIKA("/dodatak/DodatciZaposlenika.fxml"),
    DODAJ_UREDI_DODATAK_ZAPOSLENIKA("/dodatak/DodajUrediDodatakZaposlenika.fxml"),
    OBUSTAVE_ZAPOSLENIKA("/obustava/ObustaveZaposlenika.fxml"),
    DODAJ_UREDI_OBUSTAVU_ZAPOSLENIKA("/obustava/DodajUrediObustavuZaposlenika.fxml"),
    OLAKSICE_ZAPOSLENIKA("/olaksica/OlaksiceZaposlenika.fxml"),
    DODAJ_UREDI_OLAKSICU_ZAPOSLENIKA("/olaksica/DodajUrediOlaksicuZaposlenika.fxml"),
    PREBIVALISTA_ZAPOSLENIKA("/prebivaliste/PrebivalistaZaposlenika.fxml"),
    DODAJ_UREDI_PREBIVALISTE_ZAPSOLENIKA("/prebivaliste/DodajUrediPrebivalisteZaposlenika.fxml"),
    PREKOVREMENI_RADOVI_ZAPOSLENIKA("/prekovremenirad/PrekovremeniRadoviZaposlenika.fxml"),
    DODAJ_UREDI_PREKOVREMENI_RAD_ZAPOSLENIKA("/prekovremenirad/DodajUrediPrekovremeniRadZaposlenika.fxml"),
    UGOVORI_ZAPOSLENIKA("/ugovor/UgovoriZaposlenika.fxml"),
    UGOVORI_O_RADU_ZAPOSLENIKA("/ugovororadu/UgovoriORaduZaposlenika.fxml"),
    DODAJ_UREDI_UGOVOR_O_RADU_ZAPOSLENIKA("/ugovororadu/DodajUrediUgovorORaduZaposlenika.fxml"),
    UGOVORI_O_DJELU_ZAPOSLENIKA("/ugovorodjelu/UgovoriODjeluZaposlenika.fxml"),
    DODAJ_UREDI_UGOVOR_O_DJELU_ZAPOSLENIKA("/ugovorodjelu/DodajUrediUgovorODjeluZaposlenika.fxml"),
    STUDENTSKI_UGOVORI_ZAPOSLENIKA("/studentskiugovor/StudentskiUgovoriZaposlenika.fxml"),
    DODAJ_UREDI_STUDENTSKI_UGOVOR_ZAPOSLENIKA("/studentskiugovor/DodajUrediStudentskiUgovorZaposlenika.fxml"),
    POSLOVNI_PARTNERI("/poslovnipartner/PoslovniPartneri.fxml"),
    DODAJ_UREDI_POSLOVNOG_PARTNERA("/poslovnipartner/DodajUrediPoslovnogPartnera.fxml"),
    POVIJEST_PRIJAVA("/povijestprijava/PovijestPrijava.fxml"),
    ROLE_ZAPOSLENIKA("/zaposlenikrola/RoleZaposlenika.fxml"),
    DODAJ_UREDI_ROLU_ZAPOSLENIKA("/zaposlenikrola/DodajUrediRoluZaposlenika.fxml"),
    KATEGORIJE_TRANSAKCIJA("/kategorijatransakcije/KategorijeTransakcija.fxml"),
    DODAJ_UREDI_KATEGORIJU_TRANSAKCIJE("/kategorijatransakcije/DodajUrediKategorijuTransakcije.fxml"),
    TRANSAKCIJE("/transakcija/Transakcije.fxml"),
    EKSPORTIRAJ_TRANSAKCIJE_U_PDF("/transakcija/EksportirajTransakcijeUPdf.fxml"),
    DODAJ_UREDI_TRANSKACIJU("/transakcija/DodajUrediTransakciju.fxml"),
    PARAMETRI_ZA_OBRACUN_PLACE("/parametrizaobracunplace/ParametriZaObracunPlace.fxml"),
    OBRACUNI_UGOVORA("/obracunugovora/ObracuniUgovora.fxml"),
    OBRACUNI_UGOVORA_O_RADU("/obracunugovoraoradu/ObracuniUgovoraORadu.fxml"),
    DODAJ_OBRACUN_UGOVORA_O_RADU("/obracunugovoraoradu/DodajObracunUgovoraORadu.fxml"),
    ISPLATNE_LISTE("/isplatnalista/IsplatneListe.fxml"),
    ISPLATNE_LISTE_ZAPOSLENIKA("/isplatnalista/IsplatneListeZaposlenika.fxml"),
    OBRACUNI_UGOVORA_O_DJELU("/obracunugovoraodjelu/ObracuniUgovoraODjelu.fxml"),
    DODAJ_OBRACUN_UGOVORA_O_DJELU("/obracunugovoraodjelu/DodajObracunUgovoraODjelu.fxml"),
    OBRACUNI_STUDENTSKIH_UGOVORA("/obracunstudentskihugovora/ObracuniStudentskihUgovora.fxml"),
    DODAJ_OBRACUN_STUDENTSKIH_UGOVORA("/obracunstudentskihugovora/DodajObracunStudentskihUgovora.fxml"),
    PODACI_O_TVRTKI("/podaciotvrtki/PodaciOTvrtki.fxml"),
    OPSEZNI_PODACI_ZAPOSLENIKA("/podacizaposlenika/OpsezniPodaciZaposlenika.fxml"),
    OSNOVNI_PODACI_ZAPOSLENIKA("/podacizaposlenika/OsnovniPodaciZaposlenika.fxml");

    private String path;

    private FxmlView(String path) {
        this.path = path;
    }

    public String getPath() {
        return "/com/bzaja/ljudskiresursiiposlovniprocesijavafx/feature" + path;
    }
}
