package com.bzaja.ljudskiresursiiposlovniprocesilibrary.feature.obracunstudentskihugovora;

import com.bzaja.ljudskiresursiiposlovniprocesilibrary.feature.obracunugovora.ObracunUgovoraKalkulator;

public interface ObracunStudentskihUgovoraKalkulator extends ObracunUgovoraKalkulator<ObracunStudentskihUgovoraResultDto> {

}
