package com.bzaja.ljudskiresursiiposlovniprocesilibrary.feature.obracunstudentskihugovora;

import com.bzaja.ljudskiresursiiposlovniprocesilibrary.feature.obracunugovora.ObracunUgovoraMaker;

public interface ObracunStudentskihUgovoraMaker extends ObracunUgovoraMaker<ObracunStudentskihUgovora, AddObracunStudentskihUgovoraDto> {

}
